# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_sub_lesson',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='current_lesson',
            field=models.IntegerField(),
        ),
    ]
