# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('regex', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('regex', models.TextField()),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_lessons', to='algo_app.Lesson')),
            ],
        ),
    ]
