# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-26 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='regex',
        ),
        migrations.RemoveField(
            model_name='sub_lesson',
            name='regex',
        ),
        migrations.AddField(
            model_name='answer',
            name='lessons',
            field=models.ManyToManyField(related_name='answers', to='algo_app.Lesson'),
        ),
        migrations.AddField(
            model_name='answer',
            name='sub_lessons',
            field=models.ManyToManyField(related_name='answers', to='algo_app.Sub_lesson'),
        ),
    ]
